export default interface Logs {
    id:number,
    integrationId: number,
    integrationName: string,
    refId1: number,
    refName1: string,
    refId2: number,
    refName2: string,
    message: string,
    url: string,
    msgRequest: string,
    msgResponse: string,
    status: string,
    date: Date,
    time: string,
    favorite : string
    visible: string,
    requestMethod: string,
    contentType: string,
    urlReinstate: string,
    reinstate: string,
  }